"""C99 code generator: ``<name>.h`` + ``<name>.c`` without dynamic memory.

Structures hold raw register values (scaling is documented in comments and
``_SCALE``/``_OFFSET`` macros). Encode/decode functions implement constants,
LENGTH and CRC fields exactly like the engine; the tests compile the output
and compare it byte for byte with the Python encoder.
"""

from __future__ import annotations

from typing import Dict, List

from ... import __version__
from ...protocol.model import Encoding, FieldType
from .plan import FieldPlan, FramePlan, ProtocolPlan, snake

_CUSTOM_C = {
    "SUM8": ("uint8_t", "uint8_t s = 0; for (size_t i = 0; i < n; ++i) s = (uint8_t)(s + d[i]); return s;"),
    "SUM16": ("uint16_t", "uint16_t s = 0; for (size_t i = 0; i < n; ++i) s = (uint16_t)(s + d[i]); return s;"),
    "XOR8": ("uint8_t", "uint8_t s = 0; for (size_t i = 0; i < n; ++i) s ^= d[i]; return s;"),
    "TWOS_COMPLEMENT8": ("uint8_t", "uint8_t s = 0; for (size_t i = 0; i < n; ++i) s = (uint8_t)(s + d[i]); return (uint8_t)(0u - s);"),
}


def c_member(fp: FieldPlan) -> List[str]:
    comment = f"  /* {fp.comment} */" if fp.comment else ""
    if fp.kind == "bytes":
        if fp.variable:
            return [f"    uint8_t {fp.ident}[{fp.max_size or 1}];{comment}", f"    size_t {fp.ident}_len;"]
        return [f"    uint8_t {fp.ident}[{fp.size}];{comment}"]
    if fp.kind == "string":
        n = fp.max_size if fp.variable else fp.size
        return [f"    char {fp.ident}[{n} + 1];{comment}"]
    return [f"    {c_type(fp)} {fp.ident};{comment}"]


def c_type(fp: FieldPlan) -> str:
    if fp.kind == "float":
        return "float" if fp.field.type == FieldType.FLOAT32 else "double"
    if fp.kind == "bool":
        return "bool"
    if fp.kind == "int":
        return f"int{fp.storage_bits}_t"
    return f"uint{fp.storage_bits}_t"


def _bytes_literal(data: bytes) -> str:
    return "{ " + ", ".join(f"0x{b:02X}u" for b in data) + " }"


def _crc_call(alg_name: str, prefix: str) -> str:
    return f"{prefix}_crc_{alg_name.lower()}"


class CGenerator:
    def __init__(self, plan: ProtocolPlan, basename: str):
        self.plan = plan
        self.basename = basename
        self.p = plan.prefix
        self.fn = plan.prefix  # function prefix

    # ------------------------------------------------------------ header ---

    def header(self) -> str:
        p = self.plan
        guard = f"{self.p}_H"
        out = [
            f"/* {self.basename}.h - generated by Protocol Designer & Analyzer {__version__}",
            f" * Protocol: {p.protocol.name} v{p.protocol.version}",
            " * Do not edit: regenerate from the protocol definition instead. */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdbool.h>",
            "#include <stddef.h>",
            "#include <stdint.h>",
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
        ]
        for e in p.enums:
            out.append(f"/* Enumeration {e.name} */")
            out.append("typedef enum")
            out.append("{")
            items = list(e.values.items())
            for i, (value, label) in enumerate(items):
                sep = "," if i < len(items) - 1 else ""
                out.append(f"    {self.p}_{e.const_name}_{snake(label).upper()} = 0x{value:X}{sep}")
            out.append(f"}} {e.type_name}_t;")
            out.append("")

        out.append("/* Message identifiers returned by Identify() */")
        out.append("typedef enum")
        out.append("{")
        out.append(f"    {self.p}_MSG_NONE = 0,")
        for i, fp in enumerate(p.frames):
            sep = "," if i < len(p.frames) - 1 else ""
            out.append(f"    {self.p}_MSG_{fp.const_name} = {i + 1}{sep}")
        out.append(f"}} {p.type_prefix}MessageType_t;")
        out.append("")

        for fr in p.frames:
            out += self._frame_macros(fr)
            out.append("typedef struct")
            out.append("{")
            members = [line for fp in fr.user_fields for line in c_member(fp)]
            out += members or ["    uint8_t reserved_; /* message has no user fields */"]
            out.append(f"}} {fr.type_name}_t;")
            out.append("")
            out.append(
                f"bool {self.fn}_Encode_{self._fname(fr)}(const {fr.type_name}_t *msg, uint8_t *buffer, "
                "size_t capacity, size_t *length);"
            )
            out.append(f"bool {self.fn}_Decode_{self._fname(fr)}(const uint8_t *buffer, size_t length, {fr.type_name}_t *msg);")
            out.append("")

        out.append("/* Returns the message type of one complete frame, or *_MSG_NONE. */")
        out.append(f"{p.type_prefix}MessageType_t {self.fn}_Identify(const uint8_t *buffer, size_t length);")
        out.append("")
        for alg in p.crcs:
            ctype = "uint64_t" if alg.custom is None else _CUSTOM_C[alg.name][0]
            out.append(f"{ctype} {_crc_call(alg.name, self.fn)}(const uint8_t *d, size_t n);")
        out += ["", "#ifdef __cplusplus", "}", "#endif", "", f"#endif /* {guard} */", ""]
        return "\n".join(out)

    def _fname(self, fr: FramePlan) -> str:
        return fr.type_name[len(self.plan.type_prefix):] or fr.type_name

    def _frame_macros(self, fr: FramePlan) -> List[str]:
        name = f"{self.p}_{fr.const_name}"
        out = [f"/* Message {fr.frame.name}" + (f": {fr.frame.description}" if fr.frame.description else "") + " */"]
        if fr.frame.id is not None:
            out.append(f"#define {name}_ID 0x{fr.frame.id:X}u")
        if fr.frame.can_id is not None:
            out.append(f"#define {name}_CAN_ID 0x{fr.frame.can_id:X}u")
        out.append(f"#define {name}_MIN_SIZE {fr.min_size}u")
        out.append(f"#define {name}_MAX_SIZE {fr.max_size}u")
        for fp in fr.fields:
            f = fp.field
            if f.is_scaled:
                out.append(f"#define {name}_{fp.ident.upper()}_SCALE ({f.scale!r})")
                out.append(f"#define {name}_{fp.ident.upper()}_OFFSET ({f.value_offset!r})")
            for bit in f.bits:
                bname = f"{name}_{fp.ident.upper()}_{snake(bit.name).upper()}"
                out.append(f"#define {bname}_SHIFT {bit.start}u")
                out.append(f"#define {bname}_MASK 0x{bit.mask:X}u")
        return out

    # ------------------------------------------------------------ source ---

    def source(self) -> str:
        p = self.plan
        out = [
            f"/* {self.basename}.c - generated by Protocol Designer & Analyzer {__version__}",
            f" * Protocol: {p.protocol.name} v{p.protocol.version} */",
            f'#include "{self.basename}.h"',
            "",
            "#include <string.h>",
            "",
            "static inline void pd_put(uint8_t *p, uint64_t v, size_t size, bool little)",
            "{",
            "    for (size_t i = 0; i < size; ++i)",
            "    {",
            "        uint8_t b = (uint8_t)(v >> (8u * i));",
            "        p[little ? i : (size - 1u - i)] = b;",
            "    }",
            "}",
            "",
            "static inline uint64_t pd_get(const uint8_t *p, size_t size, bool little)",
            "{",
            "    uint64_t v = 0;",
            "    for (size_t i = 0; i < size; ++i)",
            "    {",
            "        v |= (uint64_t)p[little ? i : (size - 1u - i)] << (8u * i);",
            "    }",
            "    return v;",
            "}",
            "",
            "static inline int64_t pd_get_signed(const uint8_t *p, size_t size, bool little)",
            "{",
            "    uint64_t v = pd_get(p, size, little);",
            "    if (size < 8u && (v & ((uint64_t)1u << (8u * size - 1u))))",
            "    {",
            "        v |= ~(uint64_t)0u << (8u * size);",
            "    }",
            "    return (int64_t)v;",
            "}",
            "",
            "static inline void pd_put_f32(uint8_t *p, float f, bool little)",
            "{",
            "    uint32_t v;",
            "    memcpy(&v, &f, sizeof v);",
            "    pd_put(p, v, 4u, little);",
            "}",
            "",
            "static inline float pd_get_f32(const uint8_t *p, bool little)",
            "{",
            "    uint32_t v = (uint32_t)pd_get(p, 4u, little);",
            "    float f;",
            "    memcpy(&f, &v, sizeof f);",
            "    return f;",
            "}",
            "",
            "static inline void pd_put_f64(uint8_t *p, double f, bool little)",
            "{",
            "    uint64_t v;",
            "    memcpy(&v, &f, sizeof v);",
            "    pd_put(p, v, 8u, little);",
            "}",
            "",
            "static inline double pd_get_f64(const uint8_t *p, bool little)",
            "{",
            "    uint64_t v = pd_get(p, 8u, little);",
            "    double f;",
            "    memcpy(&f, &v, sizeof f);",
            "    return f;",
            "}",
            "",
        ]
        if any(a.custom is None for a in p.crcs):
            out += [
                "static inline uint64_t pd_reflect(uint64_t v, unsigned width)",
                "{",
                "    uint64_t r = 0;",
                "    for (unsigned i = 0; i < width; ++i)",
                "    {",
                "        r = (r << 1) | (v & 1u);",
                "        v >>= 1;",
                "    }",
                "    return r;",
                "}",
                "",
                "static uint64_t pd_crc(unsigned width, uint64_t poly, uint64_t init, bool refin, bool refout,",
                "                       uint64_t xorout, const uint8_t *d, size_t n)",
                "{",
                "    const uint64_t top = (uint64_t)1u << (width - 1u);",
                "    const uint64_t mask = (width >= 64u) ? ~(uint64_t)0u : (((uint64_t)1u << width) - 1u);",
                "    uint64_t crc = init & mask;",
                "    for (size_t i = 0; i < n; ++i)",
                "    {",
                "        uint8_t b = refin ? (uint8_t)pd_reflect(d[i], 8u) : d[i];",
                "        for (int bit = 7; bit >= 0; --bit)",
                "        {",
                "            uint64_t in = (uint64_t)((b >> bit) & 1u);",
                "            uint64_t msb = (crc & top) ? 1u : 0u;",
                "            crc = (crc << 1) & mask;",
                "            if (msb ^ in)",
                "            {",
                "                crc ^= poly;",
                "            }",
                "        }",
                "    }",
                "    if (refout)",
                "    {",
                "        crc = pd_reflect(crc, width);",
                "    }",
                "    return (crc ^ xorout) & mask;",
                "}",
                "",
            ]
        for alg in p.crcs:
            name = _crc_call(alg.name, self.fn)
            if alg.custom is None:
                out += [
                    f"uint64_t {name}(const uint8_t *d, size_t n)",
                    "{",
                    f"    /* {alg.name}: width={alg.width} poly=0x{alg.poly:X} init=0x{alg.init:X} "
                    f"refin={str(alg.refin).lower()} refout={str(alg.refout).lower()} xorout=0x{alg.xorout:X} */",
                    f"    return pd_crc({alg.width}u, 0x{alg.poly:X}u, 0x{alg.init:X}u, {str(alg.refin).lower()}, "
                    f"{str(alg.refout).lower()}, 0x{alg.xorout:X}u, d, n);",
                    "}",
                    "",
                ]
            else:
                ctype, body = _CUSTOM_C[alg.name]
                out += [f"{ctype} {name}(const uint8_t *d, size_t n)", "{", f"    {body}", "}", ""]
        for fr in p.frames:
            out += self._encode(fr)
            out += self._decode(fr)
        out += self._identify()
        return "\n".join(out)

    def _crc_expr(self, fr: FramePlan, fp: FieldPlan) -> str:
        s, e = fp.range_start, fp.range_end
        return f"(uint64_t){_crc_call(fp.crc.name, self.fn)}(&buffer[off[{s}]], (off[{e}] + sz[{e}]) - off[{s}])"

    def _encode(self, fr: FramePlan) -> List[str]:
        n = len(fr.fields)
        out = [
            f"bool {self.fn}_Encode_{self._fname(fr)}(const {fr.type_name}_t *msg, uint8_t *buffer, size_t capacity, size_t *length)",
            "{",
            f"    size_t off[{n}];",
            f"    size_t sz[{n}];",
            "    size_t pos = 0;",
            "    (void)off; /* unused when the message has no LENGTH/CRC field */",
            "    if (msg == NULL || buffer == NULL || length == NULL)",
            "    {",
            "        return false;",
            "    }",
        ]
        if not fr.user_fields:
            out.append("    (void)msg;")
        for fp in fr.fields:
            i = fp.index
            le = "true" if fp.little else "false"
            out.append(f"    /* {fp.name} */")
            if fp.variable:
                if fp.kind == "bytes":
                    out.append(f"    if (msg->{fp.ident}_len > {fp.max_size}u)")
                    out.append("    {")
                    out.append("        return false;")
                    out.append("    }")
                    out.append(f"    sz[{i}] = msg->{fp.ident}_len;")
                else:
                    out.append(f"    sz[{i}] = strlen(msg->{fp.ident});")
                    out.append(f"    if (sz[{i}] > {fp.max_size}u)")
                    out.append("    {")
                    out.append("        return false;")
                    out.append("    }")
            else:
                out.append(f"    sz[{i}] = {fp.size}u;")
            out += [
                f"    if (pos + sz[{i}] > capacity)",
                "    {",
                "        return false;",
                "    }",
                f"    off[{i}] = pos;",
            ]
            if fp.encoding == Encoding.CONSTANT:
                out.append("    {")
                out.append(f"        static const uint8_t k[{len(fp.const)}] = {_bytes_literal(fp.const)};")
                out.append("        memcpy(&buffer[pos], k, sizeof k);")
                out.append("    }")
            elif fp.encoding in (Encoding.LENGTH, Encoding.CRC):
                out.append(f"    memset(&buffer[pos], 0, sz[{i}]);")
            elif fp.kind == "bytes":
                out.append(f"    memcpy(&buffer[pos], msg->{fp.ident}, sz[{i}]);")
            elif fp.kind == "string":
                if fp.variable:
                    out.append(f"    memcpy(&buffer[pos], msg->{fp.ident}, sz[{i}]);")
                else:
                    out.append(f"    memset(&buffer[pos], 0, sz[{i}]);")
                    out.append("    {")
                    out.append(f"        size_t len = strlen(msg->{fp.ident});")
                    out.append(f"        if (len > sz[{i}])")
                    out.append("        {")
                    out.append("            return false;")
                    out.append("        }")
                    out.append(f"        memcpy(&buffer[pos], msg->{fp.ident}, len);")
                    out.append("    }")
            elif fp.kind == "float":
                fn = "pd_put_f32" if fp.field.type == FieldType.FLOAT32 else "pd_put_f64"
                out.append(f"    {fn}(&buffer[pos], msg->{fp.ident}, {le});")
            elif fp.kind == "bool":
                out.append(f"    pd_put(&buffer[pos], msg->{fp.ident} ? 1u : 0u, sz[{i}], {le});")
            elif fp.kind == "int":
                out.append(f"    pd_put(&buffer[pos], (uint64_t)(int64_t)msg->{fp.ident}, sz[{i}], {le});")
            else:
                if fp.size and fp.size * 8 < fp.storage_bits:
                    limit = (1 << (fp.size * 8)) - 1
                    out.append(f"    if ((uint64_t)msg->{fp.ident} > 0x{limit:X}u)")
                    out.append("    {")
                    out.append("        return false;")
                    out.append("    }")
                out.append(f"    pd_put(&buffer[pos], (uint64_t)msg->{fp.ident}, sz[{i}], {le});")
            out.append(f"    pos += sz[{i}];")
        for fp in fr.fields:
            if fp.encoding != Encoding.LENGTH:
                continue
            i, s, e = fp.index, fp.range_start, fp.range_end
            le = "true" if fp.little else "false"
            covered = f"((off[{e}] + sz[{e}]) - off[{s}])" if s <= e else "0"
            limit = (1 << (8 * fp.size)) - 1
            out += [
                "    {",
                f"        int64_t value = (int64_t){covered} + ({fp.length_adjust});",
                f"        if (value < 0 || (uint64_t)value > 0x{limit:X}u)",
                "        {",
                "            return false;",
                "        }",
                f"        pd_put(&buffer[off[{i}]], (uint64_t)value, sz[{i}], {le});",
                "    }",
            ]
        for fp in fr.fields:
            if fp.encoding == Encoding.CRC:
                le = "true" if fp.little else "false"
                out.append(f"    pd_put(&buffer[off[{fp.index}]], {self._crc_expr(fr, fp)}, sz[{fp.index}], {le});")
        out += ["    *length = pos;", "    return true;", "}", ""]
        return out

    def _decode(self, fr: FramePlan) -> List[str]:
        n = len(fr.fields)
        out = [
            f"bool {self.fn}_Decode_{self._fname(fr)}(const uint8_t *buffer, size_t length, {fr.type_name}_t *msg)",
            "{",
            f"    size_t off[{n}];",
            f"    size_t sz[{n}];",
            "    size_t pos = 0;",
            "    (void)off;",
            "    if (buffer == NULL || msg == NULL)",
            "    {",
            "        return false;",
            "    }",
            "    memset(msg, 0, sizeof(*msg));",
        ]
        for fp in fr.fields:
            i = fp.index
            if fp.variable:
                if fp.length_field is not None:
                    lp = fr.fields[fp.length_field]
                    others = sum(fr.fields[j].size or 0 for j in range(lp.range_start, lp.range_end + 1) if j != i)
                    le = "true" if lp.little else "false"
                    out += [
                        "    {",
                        f"        int64_t v = (int64_t)pd_get(&buffer[off[{lp.index}]], sz[{lp.index}], {le}) - ({lp.length_adjust}) - {others};",
                        f"        if (v < 0 || v > {fp.max_size})",
                        "        {",
                        "            return false;",
                        "        }",
                        f"        sz[{i}] = (size_t)v;",
                        "    }",
                    ]
                else:
                    trailing = sum(x.size or 0 for x in fr.fields[i + 1 :])
                    out += [
                        f"    if (length < pos + {trailing}u)",
                        "    {",
                        "        return false;",
                        "    }",
                        f"    sz[{i}] = length - pos - {trailing}u;",
                        f"    if (sz[{i}] > {fp.max_size}u)",
                        "    {",
                        "        return false;",
                        "    }",
                    ]
            else:
                out.append(f"    sz[{i}] = {fp.size}u;")
            out += [
                f"    if (pos + sz[{i}] > length)",
                "    {",
                "        return false;",
                "    }",
                f"    off[{i}] = pos;",
            ]
            if fp.encoding == Encoding.CONSTANT:
                out += [
                    "    {",
                    f"        static const uint8_t k[{len(fp.const)}] = {_bytes_literal(fp.const)};",
                    "        if (memcmp(&buffer[pos], k, sizeof k) != 0)",
                    "        {",
                    "            return false;",
                    "        }",
                    "    }",
                ]
            out.append(f"    pos += sz[{i}];")
        out += ["    if (pos != length)", "    {", "        return false;", "    }"]
        for fp in fr.fields:
            le = "true" if fp.little else "false"
            if fp.encoding == Encoding.LENGTH:
                s, e = fp.range_start, fp.range_end
                covered = f"((off[{e}] + sz[{e}]) - off[{s}])" if s <= e else "0"
                out += [
                    f"    if ((int64_t)pd_get(&buffer[off[{fp.index}]], sz[{fp.index}], {le}) != (int64_t){covered} + ({fp.length_adjust}))",
                    "    {",
                    "        return false;",
                    "    }",
                ]
            elif fp.encoding == Encoding.CRC:
                out += [
                    f"    if (pd_get(&buffer[off[{fp.index}]], sz[{fp.index}], {le}) != {self._crc_expr(fr, fp)})",
                    "    {",
                    "        return false;",
                    "    }",
                ]
        for fp in fr.user_fields:
            i = fp.index
            le = "true" if fp.little else "false"
            src = f"&buffer[off[{i}]]"
            if fp.kind == "bytes":
                out.append(f"    memcpy(msg->{fp.ident}, {src}, sz[{i}]);")
                if fp.variable:
                    out.append(f"    msg->{fp.ident}_len = sz[{i}];")
            elif fp.kind == "string":
                out.append(f"    memcpy(msg->{fp.ident}, {src}, sz[{i}]);")
                out.append(f"    msg->{fp.ident}[sz[{i}]] = '\\0';")
            elif fp.kind == "float":
                fn = "pd_get_f32" if fp.field.type == FieldType.FLOAT32 else "pd_get_f64"
                out.append(f"    msg->{fp.ident} = {fn}({src}, {le});")
            elif fp.kind == "bool":
                out.append(f"    msg->{fp.ident} = pd_get({src}, sz[{i}], {le}) != 0u;")
            elif fp.kind == "int":
                out.append(f"    msg->{fp.ident} = ({c_type(fp)})pd_get_signed({src}, sz[{i}], {le});")
            else:
                out.append(f"    msg->{fp.ident} = ({c_type(fp)})pd_get({src}, sz[{i}], {le});")
        out += ["    return true;", "}", ""]
        return out

    def _identify(self) -> List[str]:
        p = self.plan
        ordered = sorted(p.frames, key=lambda fr: -sum(1 for f in fr.fields if f.encoding == Encoding.CONSTANT))
        out = [
            f"{p.type_prefix}MessageType_t {self.fn}_Identify(const uint8_t *buffer, size_t length)",
            "{",
            "    union",
            "    {",
        ]
        for fr in p.frames:
            out.append(f"        {fr.type_name}_t m_{fr.const_name.lower()};")
        if not p.frames:
            out.append("        uint8_t unused_;")
        out += ["    } scratch;", ""]
        for fr in ordered:
            out += [
                f"    if ({self.fn}_Decode_{self._fname(fr)}(buffer, length, &scratch.m_{fr.const_name.lower()}))",
                "    {",
                f"        return {self.p}_MSG_{fr.const_name};",
                "    }",
            ]
        if not p.frames:
            out += ["    (void)buffer;", "    (void)length;", "    (void)scratch;"]
        out += [f"    return {self.p}_MSG_NONE;", "}", ""]
        return out


def generate_c(plan: ProtocolPlan, basename: str) -> Dict[str, str]:
    gen = CGenerator(plan, basename)
    return {f"{basename}.h": gen.header(), f"{basename}.c": gen.source()}
