"""C++17 generator: type-safe wrappers around the generated C code."""

from __future__ import annotations

from typing import Dict

from ... import __version__
from .c_gen import generate_c
from .plan import ProtocolPlan, pascal, snake


def generate_cpp(plan: ProtocolPlan, basename: str) -> Dict[str, str]:
    files = generate_c(plan, basename)
    ns = snake(plan.prefix)
    out = [
        f"// {basename}.hpp - generated by Protocol Designer & Analyzer {__version__}",
        f"// Protocol: {plan.protocol.name} v{plan.protocol.version}",
        f"// C++17 wrappers; compile {basename}.c together with your C++ sources.",
        "#pragma once",
        "",
        f'#include "{basename}.h"',
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <stdexcept>",
        "#include <vector>",
        "",
        f"namespace {ns}",
        "{",
        "",
    ]
    for fr in plan.frames:
        fname = fr.type_name[len(plan.type_prefix):] or fr.type_name
        cls = pascal(fr.frame.name)
        out += [
            f"/// {fr.frame.name}" + (f" - {fr.frame.description}" if fr.frame.description else ""),
            f"struct {cls} : public {fr.type_name}_t",
            "{",
            f"    static constexpr const char *kName = \"{fr.frame.name}\";",
            f"    static constexpr std::size_t kMaxSize = {fr.max_size}u;",
            "",
            f"    {cls}() : {fr.type_name}_t{{}} {{}}",
            "",
            "    /// Encodes the message; throws std::invalid_argument when a value does not fit.",
            "    std::vector<std::uint8_t> encode() const",
            "    {",
            "        std::vector<std::uint8_t> buffer(kMaxSize == 0u ? 1u : kMaxSize);",
            "        std::size_t length = 0;",
            f"        if (!{plan.prefix}_Encode_{fname}(this, buffer.data(), buffer.size(), &length))",
            "        {",
            f"            throw std::invalid_argument(\"cannot encode {fr.frame.name}\");",
            "        }",
            "        buffer.resize(length);",
            "        return buffer;",
            "    }",
            "",
            "    /// Decodes one complete frame; returns std::nullopt when it is not a valid frame.",
            f"    static std::optional<{cls}> decode(const std::uint8_t *data, std::size_t length)",
            "    {",
            f"        {cls} msg;",
            f"        if (!{plan.prefix}_Decode_{fname}(data, length, &msg))",
            "        {",
            "            return std::nullopt;",
            "        }",
            "        return msg;",
            "    }",
            "",
            f"    static std::optional<{cls}> decode(const std::vector<std::uint8_t> &data)",
            "    {",
            "        return decode(data.data(), data.size());",
            "    }",
            "};",
            "",
        ]
    out += [
        f"inline {plan.type_prefix}MessageType_t identify(const std::vector<std::uint8_t> &data)",
        "{",
        f"    return {plan.prefix}_Identify(data.data(), data.size());",
        "}",
        "",
        f"}} // namespace {ns}",
        "",
    ]
    files[f"{basename}.hpp"] = "\n".join(out)
    return files
