"""C# generator: one file, classes with Encode() / TryDecode()."""

from __future__ import annotations

from typing import Dict, List

from ... import __version__
from ...protocol.model import Encoding, FieldType
from .plan import RESERVED, FieldPlan, FramePlan, ProtocolPlan, pascal, snake

_CS_INT = {
    ("uint", 8): "byte", ("uint", 16): "ushort", ("uint", 32): "uint", ("uint", 64): "ulong",
    ("int", 8): "sbyte", ("int", 16): "short", ("int", 32): "int", ("int", 64): "long",
}
_CUSTOM_CS = {
    "SUM8": "ulong s = 0; for (int i = 0; i < n; i++) s += d[o + i]; return s & 0xFF;",
    "SUM16": "ulong s = 0; for (int i = 0; i < n; i++) s += d[o + i]; return s & 0xFFFF;",
    "XOR8": "ulong s = 0; for (int i = 0; i < n; i++) s ^= d[o + i]; return s;",
    "TWOS_COMPLEMENT8": "ulong s = 0; for (int i = 0; i < n; i++) s += d[o + i]; return (0x100 - (s & 0xFF)) & 0xFF;",
}


def cs_type(fp: FieldPlan) -> str:
    if fp.kind == "bytes":
        return "byte[]"
    if fp.kind == "string":
        return "string"
    if fp.kind == "bool":
        return "bool"
    if fp.kind == "float":
        return "float" if fp.field.type == FieldType.FLOAT32 else "double"
    return _CS_INT[(fp.kind, fp.storage_bits)]


def _cs_default(fp: FieldPlan) -> str:
    if fp.kind == "bytes":
        return f" = new byte[{0 if fp.variable else fp.size}];"
    if fp.kind == "string":
        return ' = "";'
    return ";"


def _bool(v: bool) -> str:
    return "true" if v else "false"


_CS_MEMBERS = {"MessageName", "MessageId", "MessageCanId", "Encode", "TryDecode", "Equals", "GetHashCode",
               "ToString", "GetType"}


def _prop(fp: FieldPlan, cls: str = "") -> str:
    name = pascal(fp.name)
    if name in _CS_MEMBERS or name == cls or name.lower() in RESERVED:
        name += "Value"
    return name


def generate_csharp(plan: ProtocolPlan, basename: str) -> Dict[str, str]:
    ns = pascal(plan.prefix)
    out: List[str] = [
        f"// {basename}.cs - generated by Protocol Designer & Analyzer {__version__}",
        f"// Protocol: {plan.protocol.name} v{plan.protocol.version}",
        "// Do not edit: regenerate from the protocol definition instead.",
        "using System;",
        "using System.Text;",
        "",
        f"namespace {ns}",
        "{",
    ]
    for e in plan.enums:
        out.append(f"    public enum {pascal(e.name)} : ulong")
        out.append("    {")
        for value, label in e.values.items():
            out.append(f"        {snake(label).upper()} = 0x{value:X},")
        out.append("    }")
        out.append("")

    out += [
        "    internal static class Codec",
        "    {",
        "        public static void Put(byte[] b, int pos, ulong v, int size, bool little)",
        "        {",
        "            for (int i = 0; i < size; i++)",
        "            {",
        "                b[little ? pos + i : pos + size - 1 - i] = (byte)(v >> (8 * i));",
        "            }",
        "        }",
        "",
        "        public static ulong Get(byte[] b, int pos, int size, bool little)",
        "        {",
        "            ulong v = 0;",
        "            for (int i = 0; i < size; i++)",
        "            {",
        "                v |= (ulong)b[little ? pos + i : pos + size - 1 - i] << (8 * i);",
        "            }",
        "            return v;",
        "        }",
        "",
        "        public static long GetSigned(byte[] b, int pos, int size, bool little)",
        "        {",
        "            ulong v = Get(b, pos, size, little);",
        "            if (size < 8 && (v & (1UL << (8 * size - 1))) != 0)",
        "            {",
        "                v |= ulong.MaxValue << (8 * size);",
        "            }",
        "            return (long)v;",
        "        }",
        "",
        "        public static bool Fits(ulong v, int size) => size >= 8 || v < (1UL << (8 * size));",
        "",
        "        public static bool Equal(byte[] b, int pos, byte[] k)",
        "        {",
        "            for (int i = 0; i < k.Length; i++)",
        "            {",
        "                if (b[pos + i] != k[i]) return false;",
        "            }",
        "            return true;",
        "        }",
        "",
        "        public static ulong Reflect(ulong v, int width)",
        "        {",
        "            ulong r = 0;",
        "            for (int i = 0; i < width; i++)",
        "            {",
        "                r = (r << 1) | (v & 1);",
        "                v >>= 1;",
        "            }",
        "            return r;",
        "        }",
        "",
        "        public static ulong Crc(int width, ulong poly, ulong init, bool refin, bool refout, ulong xorout, byte[] d, int o, int n)",
        "        {",
        "            ulong top = 1UL << (width - 1);",
        "            ulong mask = width >= 64 ? ulong.MaxValue : (1UL << width) - 1;",
        "            ulong crc = init & mask;",
        "            for (int i = 0; i < n; i++)",
        "            {",
        "                ulong b = refin ? Reflect(d[o + i], 8) : d[o + i];",
        "                for (int bit = 7; bit >= 0; bit--)",
        "                {",
        "                    ulong msb = (crc & top) != 0 ? 1UL : 0UL;",
        "                    crc = (crc << 1) & mask;",
        "                    if ((msb ^ ((b >> bit) & 1)) != 0) crc ^= poly;",
        "                }",
        "            }",
        "            if (refout) crc = Reflect(crc, width);",
        "            return (crc ^ xorout) & mask;",
        "        }",
        "    }",
        "",
        "    public static class Checksums",
        "    {",
    ]
    for alg in plan.crcs:
        name = pascal(alg.name)
        if alg.custom is None:
            out.append(
                f"        public static ulong {name}(byte[] d, int o, int n) => Codec.Crc({alg.width}, 0x{alg.poly:X}UL, "
                f"0x{alg.init:X}UL, {_bool(alg.refin)}, {_bool(alg.refout)}, 0x{alg.xorout:X}UL, d, o, n);"
            )
        else:
            out.append(f"        public static ulong {name}(byte[] d, int o, int n) {{ {_CUSTOM_CS[alg.name]} }}")
    out += ["    }", ""]

    for fr in plan.frames:
        out += _frame_class(fr)

    order = sorted(plan.frames, key=lambda fr: -sum(1 for f in fr.fields if f.encoding == Encoding.CONSTANT))
    out += [
        "    public static class Messages",
        "    {",
        "        /// <summary>Decodes one complete frame as whichever message it is, or returns null.</summary>",
        "        public static object Identify(byte[] data)",
        "        {",
    ]
    for fr in order:
        cls = pascal(fr.frame.name)
        var = "m" + cls
        out.append(f"            if ({cls}.TryDecode(data, out var {var})) return {var};")
    out += ["            return null;", "        }", "    }", "}", ""]
    return {f"{basename}.cs": "\n".join(out)}


def _frame_class(fr: FramePlan) -> List[str]:
    cls = pascal(fr.frame.name)
    n = len(fr.fields)
    out = [
        f"    /// <summary>{fr.frame.description or fr.frame.name}</summary>",
        f"    public sealed class {cls}",
        "    {",
        f'        public const string MessageName = "{fr.frame.name}";',
    ]
    if fr.frame.id is not None:
        out.append(f"        public const int MessageId = 0x{fr.frame.id:X};")
    if fr.frame.can_id is not None:
        out.append(f"        public const uint MessageCanId = 0x{fr.frame.can_id:X};")
    for fp in fr.fields:
        if fp.field.is_scaled:
            out.append(f"        public const double {_prop(fp, cls)}Scale = {fp.field.scale!r};")
            out.append(f"        public const double {_prop(fp, cls)}Offset = {fp.field.value_offset!r};")
    for fp in fr.user_fields:
        if fp.comment:
            out.append(f"        /// <summary>{fp.comment}</summary>")
        out.append(f"        public {cs_type(fp)} {_prop(fp, cls)}{_cs_default(fp)}")
    out.append("")

    # ---- Encode
    out.append("        public byte[] Encode()")
    out.append("        {")
    out.append(f"            int[] sz = new int[{n}];")
    out.append(f"            int[] off = new int[{n}];")
    for fp in fr.fields:
        if fp.kind == "string" and fp.user:
            out.append(f'            byte[] s{fp.index} = Encoding.GetEncoding("{_cs_encoding(fp)}").GetBytes({_prop(fp, cls)} ?? "");')
    for fp in fr.fields:
        i = fp.index
        if fp.variable:
            src = f"s{i}.Length" if fp.kind == "string" else f"({_prop(fp, cls)} ?? Array.Empty<byte>()).Length"
            out.append(f"            sz[{i}] = {src};")
            out.append(f'            if (sz[{i}] > {fp.max_size}) throw new ArgumentException("{fp.name} is too long");')
        else:
            out.append(f"            sz[{i}] = {fp.size};")
    out.append("            int total = 0;")
    out.append(f"            for (int i = 0; i < {n}; i++) {{ off[i] = total; total += sz[i]; }}")
    out.append("            byte[] b = new byte[total];")
    for fp in fr.fields:
        i = fp.index
        le = _bool(fp.little)
        if fp.encoding == Encoding.CONSTANT:
            out.append(f"            Array.Copy(new byte[] {{ {', '.join(f'0x{x:02X}' for x in fp.const)} }}, 0, b, off[{i}], {len(fp.const)});")
        elif fp.encoding in (Encoding.LENGTH, Encoding.CRC):
            continue
        elif fp.kind == "bytes":
            data = f"({_prop(fp, cls)} ?? Array.Empty<byte>())"
            if not fp.variable:
                out.append(f'            if ({data}.Length > {fp.size}) throw new ArgumentException("{fp.name} is too long");')
            out.append(f"            Array.Copy({data}, 0, b, off[{i}], {data}.Length);")
        elif fp.kind == "string":
            if not fp.variable:
                out.append(f'            if (s{i}.Length > {fp.size}) throw new ArgumentException("{fp.name} is too long");')
            out.append(f"            Array.Copy(s{i}, 0, b, off[{i}], s{i}.Length);")
        elif fp.kind == "float":
            if fp.field.type == FieldType.FLOAT32:
                out.append(f"            Codec.Put(b, off[{i}], (uint)BitConverter.SingleToInt32Bits({_prop(fp, cls)}), 4, {le});")
            else:
                out.append(f"            Codec.Put(b, off[{i}], (ulong)BitConverter.DoubleToInt64Bits({_prop(fp, cls)}), 8, {le});")
        elif fp.kind == "bool":
            out.append(f"            Codec.Put(b, off[{i}], {_prop(fp, cls)} ? 1UL : 0UL, {fp.size}, {le});")
        elif fp.kind == "int":
            out.append(f"            Codec.Put(b, off[{i}], unchecked((ulong)(long){_prop(fp, cls)}), {fp.size}, {le});")
        else:
            out.append(f'            if (!Codec.Fits({_prop(fp, cls)}, {fp.size})) throw new ArgumentException("{fp.name} out of range");')
            out.append(f"            Codec.Put(b, off[{i}], {_prop(fp, cls)}, {fp.size}, {le});")
    for fp in fr.fields:
        if fp.encoding == Encoding.LENGTH:
            i, s, e = fp.index, fp.range_start, fp.range_end
            covered = f"(off[{e}] + sz[{e}] - off[{s}])" if s <= e else "0"
            out.append(f"            long len{i} = (long){covered} + ({fp.length_adjust});")
            out.append(f'            if (len{i} < 0 || !Codec.Fits((ulong)len{i}, {fp.size})) throw new ArgumentException("{fp.name} out of range");')
            out.append(f"            Codec.Put(b, off[{i}], (ulong)len{i}, {fp.size}, {_bool(fp.little)});")
    for fp in fr.fields:
        if fp.encoding == Encoding.CRC:
            i, s, e = fp.index, fp.range_start, fp.range_end
            out.append(
                f"            Codec.Put(b, off[{i}], Checksums.{pascal(fp.crc.name)}(b, off[{s}], off[{e}] + sz[{e}] - off[{s}]), {fp.size}, {_bool(fp.little)});"
            )
    out.append("            return b;")
    out.append("        }")
    out.append("")

    # ---- TryDecode
    out.append(f"        public static bool TryDecode(byte[] d, out {cls} msg)")
    out.append("        {")
    out.append("            msg = null;")
    out.append("            if (d == null) return false;")
    out.append(f"            int[] sz = new int[{n}];")
    out.append(f"            int[] off = new int[{n}];")
    out.append("            int pos = 0;")
    for fp in fr.fields:
        i = fp.index
        if fp.variable:
            if fp.length_field is not None:
                lp = fr.fields[fp.length_field]
                others = sum(fr.fields[j].size or 0 for j in range(lp.range_start, lp.range_end + 1) if j != i)
                out.append(
                    f"            long v{i} = (long)Codec.Get(d, off[{lp.index}], sz[{lp.index}], {_bool(lp.little)}) - ({lp.length_adjust}) - {others};"
                )
            else:
                trailing = sum(x.size or 0 for x in fr.fields[i + 1:])
                out.append(f"            long v{i} = (long)d.Length - pos - {trailing};")
            out.append(f"            if (v{i} < 0 || v{i} > {fp.max_size}) return false;")
            out.append(f"            sz[{i}] = (int)v{i};")
        else:
            out.append(f"            sz[{i}] = {fp.size};")
        out.append(f"            if (pos + sz[{i}] > d.Length) return false;")
        out.append(f"            off[{i}] = pos;")
        if fp.encoding == Encoding.CONSTANT:
            out.append(f"            if (!Codec.Equal(d, pos, new byte[] {{ {', '.join(f'0x{x:02X}' for x in fp.const)} }})) return false;")
        out.append(f"            pos += sz[{i}];")
    out.append("            if (pos != d.Length) return false;")
    for fp in fr.fields:
        i = fp.index
        le = _bool(fp.little)
        if fp.encoding == Encoding.LENGTH:
            s, e = fp.range_start, fp.range_end
            covered = f"(off[{e}] + sz[{e}] - off[{s}])" if s <= e else "0"
            out.append(f"            if ((long)Codec.Get(d, off[{i}], sz[{i}], {le}) != (long){covered} + ({fp.length_adjust})) return false;")
        elif fp.encoding == Encoding.CRC:
            s, e = fp.range_start, fp.range_end
            out.append(
                f"            if (Codec.Get(d, off[{i}], sz[{i}], {le}) != Checksums.{pascal(fp.crc.name)}(d, off[{s}], off[{e}] + sz[{e}] - off[{s}])) return false;"
            )
    out.append(f"            var m = new {cls}();")
    for fp in fr.user_fields:
        i = fp.index
        le = _bool(fp.little)
        prop = _prop(fp, cls)
        if fp.kind == "bytes":
            out.append(f"            m.{prop} = new byte[sz[{i}]];")
            out.append(f"            Array.Copy(d, off[{i}], m.{prop}, 0, sz[{i}]);")
        elif fp.kind == "string":
            out.append(f"            int end{i} = Array.IndexOf(d, (byte)0, off[{i}], sz[{i}]);")
            out.append(f"            int len{i} = end{i} < 0 ? sz[{i}] : end{i} - off[{i}];")
            out.append(f'            m.{prop} = Encoding.GetEncoding("{_cs_encoding(fp)}").GetString(d, off[{i}], len{i});')
        elif fp.kind == "float":
            if fp.field.type == FieldType.FLOAT32:
                out.append(f"            m.{prop} = BitConverter.Int32BitsToSingle((int)(uint)Codec.Get(d, off[{i}], 4, {le}));")
            else:
                out.append(f"            m.{prop} = BitConverter.Int64BitsToDouble((long)Codec.Get(d, off[{i}], 8, {le}));")
        elif fp.kind == "bool":
            out.append(f"            m.{prop} = Codec.Get(d, off[{i}], sz[{i}], {le}) != 0;")
        elif fp.kind == "int":
            out.append(f"            m.{prop} = ({cs_type(fp)})Codec.GetSigned(d, off[{i}], sz[{i}], {le});")
        else:
            out.append(f"            m.{prop} = ({cs_type(fp)})Codec.Get(d, off[{i}], sz[{i}], {le});")
    out.append("            msg = m;")
    out.append("            return true;")
    out.append("        }")
    out.append("    }")
    out.append("")
    return out


def _cs_encoding(fp: FieldPlan) -> str:
    enc = fp.field.string_encoding.lower().replace("_", "-")
    return {"ascii": "us-ascii", "utf8": "utf-8", "latin1": "iso-8859-1", "latin-1": "iso-8859-1"}.get(enc, enc)
