"""Python code generator: one dependency-free module with dataclasses."""

from __future__ import annotations

from typing import Dict, List

from ... import __version__
from ...protocol.model import Encoding, FieldType
from .plan import FieldPlan, FramePlan, ProtocolPlan, pascal, snake

_CUSTOM_PY = {
    "SUM8": "return sum(data) & 0xFF",
    "SUM16": "return sum(data) & 0xFFFF",
    "XOR8": "result = 0\n    for b in data:\n        result ^= b\n    return result",
    "TWOS_COMPLEMENT8": "return (-sum(data)) & 0xFF",
}


def _py_default(fp: FieldPlan) -> str:
    if fp.kind == "bytes":
        return 'b""'
    if fp.kind == "string":
        return '""'
    if fp.kind == "bool":
        return "False"
    if fp.kind == "float":
        return "0.0"
    return "0"


def _py_type(fp: FieldPlan) -> str:
    return {"bytes": "bytes", "string": "str", "bool": "bool", "float": "float"}.get(fp.kind, "int")


def _endian(fp: FieldPlan) -> str:
    return '"little"' if fp.little else '"big"'


def generate_python(plan: ProtocolPlan, basename: str) -> Dict[str, str]:
    p = plan.protocol
    out: List[str] = [
        f'"""{p.name} v{p.version} - generated by Protocol Designer & Analyzer {__version__}.',
        "",
        "Do not edit: regenerate from the protocol definition instead.",
        "Fields hold raw values; see the comments for scaling (physical = raw * scale + offset).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import struct",
        "from dataclasses import dataclass",
        "from enum import IntEnum",
        "from typing import List, Optional",
        "",
        "",
        "class DecodeError(ValueError):",
        '    """The bytes are not a valid frame of the requested message."""',
        "",
        "",
    ]
    for e in plan.enums:
        out.append(f"class {pascal(e.name)}(IntEnum):")
        for value, label in e.values.items():
            out.append(f"    {snake(label).upper()} = 0x{value:X}")
        out += ["", ""]

    out += [
        "def _put_u(value: int, size: int, little: bool) -> bytes:",
        "    value = int(value)",
        "    if value < 0 or value >= 1 << (8 * size):",
        '        raise ValueError(f"{value} does not fit in {size} byte(s)")',
        '    return value.to_bytes(size, "little" if little else "big")',
        "",
        "",
        "def _put_s(value: int, size: int, little: bool) -> bytes:",
        '    return int(value).to_bytes(size, "little" if little else "big", signed=True)',
        "",
        "",
        "def _get_u(data: bytes, little: bool) -> int:",
        '    return int.from_bytes(data, "little" if little else "big")',
        "",
        "",
        "def _get_s(data: bytes, little: bool) -> int:",
        '    return int.from_bytes(data, "little" if little else "big", signed=True)',
        "",
        "",
        "def _fit(data: bytes, size: int) -> bytes:",
        "    if len(data) > size:",
        '        raise ValueError(f"{len(data)} byte(s) do not fit in {size}")',
        '    return data + b"\\x00" * (size - len(data))',
        "",
        "",
    ]
    if any(a.custom is None for a in plan.crcs):
        out += [
            "def _reflect(value: int, width: int) -> int:",
            "    result = 0",
            "    for _ in range(width):",
            "        result = (result << 1) | (value & 1)",
            "        value >>= 1",
            "    return result",
            "",
            "",
            "def _crc(width: int, poly: int, init: int, refin: bool, refout: bool, xorout: int, data: bytes) -> int:",
            "    top = 1 << (width - 1)",
            "    mask = (1 << width) - 1",
            "    crc = init & mask",
            "    for byte in data:",
            "        if refin:",
            "            byte = _reflect(byte, 8)",
            "        for bit in range(7, -1, -1):",
            "            msb = 1 if crc & top else 0",
            "            crc = (crc << 1) & mask",
            "            if msb ^ ((byte >> bit) & 1):",
            "                crc ^= poly",
            "    if refout:",
            "        crc = _reflect(crc, width)",
            "    return (crc ^ xorout) & mask",
            "",
            "",
        ]
    for alg in plan.crcs:
        out.append(f"def crc_{alg.name.lower()}(data: bytes) -> int:")
        if alg.custom is None:
            out.append(
                f"    return _crc({alg.width}, 0x{alg.poly:X}, 0x{alg.init:X}, {alg.refin}, {alg.refout}, 0x{alg.xorout:X}, data)"
            )
        else:
            out.append("    " + _CUSTOM_PY[alg.name])
        out += ["", ""]

    for fr in plan.frames:
        out += _frame_class(fr)

    out.append("MESSAGES = [" + ", ".join(pascal(fr.frame.name) for fr in plan.frames) + "]")
    order = sorted(plan.frames, key=lambda fr: -sum(1 for f in fr.fields if f.encoding == Encoding.CONSTANT))
    out += [
        "",
        "",
        "def identify(data: bytes) -> Optional[object]:",
        '    """Decode one complete frame as whichever message it is, or return None."""',
        "    for cls in [" + ", ".join(pascal(fr.frame.name) for fr in order) + "]:",
        "        try:",
        "            return cls.decode(data)",
        "        except DecodeError:",
        "            continue",
        "    return None",
        "",
    ]
    return {f"{basename}.py": "\n".join(out)}


def _frame_class(fr: FramePlan) -> List[str]:
    cls = pascal(fr.frame.name)
    n = len(fr.fields)
    out = ["@dataclass", f"class {cls}:"]
    doc = fr.frame.description or f"Message {fr.frame.name}"
    out.append(f'    """{doc}"""')
    out.append("")
    out.append(f'    NAME = "{fr.frame.name}"')
    out.append(f"    ID = {fr.frame.id if fr.frame.id is not None else None}")
    out.append(f"    CAN_ID = {hex(fr.frame.can_id) if fr.frame.can_id is not None else None}")
    for fp in fr.fields:
        if fp.field.is_scaled:
            out.append(f"    {fp.ident.upper()}_SCALE = {fp.field.scale!r}")
            out.append(f"    {fp.ident.upper()}_OFFSET = {fp.field.value_offset!r}")
    out.append("")
    for fp in fr.user_fields:
        comment = f"  # {fp.comment}" if fp.comment else ""
        out.append(f"    {fp.ident}: {_py_type(fp)} = {_py_default(fp)}{comment}")
    if fr.user_fields:
        out.append("")

    # ---- encode
    out.append("    def encode(self) -> bytes:")
    out.append(f"        sz = [0] * {n}")
    out.append(f"        chunks: List[bytes] = [b\"\"] * {n}")
    for fp in fr.fields:
        i = fp.index
        little = str(fp.little)
        if fp.encoding == Encoding.CONSTANT:
            out.append(f"        chunks[{i}] = {fp.const!r}")
        elif fp.encoding in (Encoding.LENGTH, Encoding.CRC):
            out.append(f"        chunks[{i}] = bytes({fp.size})")
        elif fp.kind == "bytes":
            if fp.variable:
                out.append(f"        chunks[{i}] = bytes(self.{fp.ident})")
                out.append(f"        if len(chunks[{i}]) > {fp.max_size}:")
                out.append(f'            raise ValueError("{fp.name} is too long")')
            else:
                out.append(f"        chunks[{i}] = _fit(bytes(self.{fp.ident}), {fp.size})")
        elif fp.kind == "string":
            enc = fp.field.string_encoding
            if fp.variable:
                out.append(f'        chunks[{i}] = self.{fp.ident}.encode("{enc}")')
                out.append(f"        if len(chunks[{i}]) > {fp.max_size}:")
                out.append(f'            raise ValueError("{fp.name} is too long")')
            else:
                out.append(f'        chunks[{i}] = _fit(self.{fp.ident}.encode("{enc}"), {fp.size})')
        elif fp.kind == "float":
            fmt = ("<" if fp.little else ">") + ("f" if fp.field.type == FieldType.FLOAT32 else "d")
            out.append(f'        chunks[{i}] = struct.pack("{fmt}", self.{fp.ident})')
        elif fp.kind == "int":
            out.append(f"        chunks[{i}] = _put_s(self.{fp.ident}, {fp.size}, {little})")
        elif fp.kind == "bool":
            out.append(f"        chunks[{i}] = _put_u(1 if self.{fp.ident} else 0, {fp.size}, {little})")
        else:
            out.append(f"        chunks[{i}] = _put_u(self.{fp.ident}, {fp.size}, {little})")
    out.append(f"        sz = [len(c) for c in chunks]")
    for fp in fr.fields:
        if fp.encoding == Encoding.LENGTH:
            s, e = fp.range_start, fp.range_end
            out.append(f"        chunks[{fp.index}] = _put_u(sum(sz[{s}:{e + 1}]) + ({fp.length_adjust}), {fp.size}, {fp.little})")
    for fp in fr.fields:
        if fp.encoding == Encoding.CRC:
            s, e = fp.range_start, fp.range_end
            out.append(
                f'        chunks[{fp.index}] = _put_u(crc_{fp.crc.name.lower()}(b"".join(chunks[{s}:{e + 1}])), {fp.size}, {fp.little})'
            )
    out.append('        return b"".join(chunks)')
    out.append("")

    # ---- decode
    out.append("    @classmethod")
    out.append(f'    def decode(cls, data: bytes) -> "{cls}":')
    out.append("        data = bytes(data)")
    out.append(f"        off = [0] * {n}")
    out.append(f"        sz = [0] * {n}")
    out.append("        pos = 0")
    for fp in fr.fields:
        i = fp.index
        if fp.variable:
            if fp.length_field is not None:
                lp = fr.fields[fp.length_field]
                others = sum(fr.fields[j].size or 0 for j in range(lp.range_start, lp.range_end + 1) if j != i)
                out.append(
                    f"        sz[{i}] = _get_u(data[off[{lp.index}]:off[{lp.index}] + sz[{lp.index}]], {lp.little})"
                    f" - ({lp.length_adjust}) - {others}"
                )
                out.append(f"        if sz[{i}] < 0 or sz[{i}] > {fp.max_size}:")
                out.append('            raise DecodeError("invalid length")')
            else:
                trailing = sum(x.size or 0 for x in fr.fields[i + 1 :])
                out.append(f"        sz[{i}] = len(data) - pos - {trailing}")
                out.append(f"        if sz[{i}] < 0 or sz[{i}] > {fp.max_size}:")
                out.append('            raise DecodeError("invalid length")')
        else:
            out.append(f"        sz[{i}] = {fp.size}")
        out.append(f"        if pos + sz[{i}] > len(data):")
        out.append(f'            raise DecodeError("frame too short at {fp.name}")')
        out.append(f"        off[{i}] = pos")
        if fp.encoding == Encoding.CONSTANT:
            out.append(f"        if data[pos:pos + sz[{i}]] != {fp.const!r}:")
            out.append(f'            raise DecodeError("{fp.name} mismatch")')
        out.append(f"        pos += sz[{i}]")
    out.append("        if pos != len(data):")
    out.append('            raise DecodeError("unexpected frame length")')
    for fp in fr.fields:
        i = fp.index
        if fp.encoding == Encoding.LENGTH:
            s, e = fp.range_start, fp.range_end
            out.append(f"        if _get_u(data[off[{i}]:off[{i}] + sz[{i}]], {fp.little}) != sum(sz[{s}:{e + 1}]) + ({fp.length_adjust}):")
            out.append(f'            raise DecodeError("{fp.name} does not match the payload size")')
        elif fp.encoding == Encoding.CRC:
            s, e = fp.range_start, fp.range_end
            out.append(
                f"        if _get_u(data[off[{i}]:off[{i}] + sz[{i}]], {fp.little}) != "
                f"crc_{fp.crc.name.lower()}(data[off[{s}]:off[{e}] + sz[{e}]]):"
            )
            out.append(f'            raise DecodeError("{fp.name} invalid")')
    args = []
    for fp in fr.user_fields:
        i = fp.index
        chunk = f"data[off[{i}]:off[{i}] + sz[{i}]]"
        if fp.kind == "bytes":
            args.append(f"{fp.ident}={chunk}")
        elif fp.kind == "string":
            args.append(f'{fp.ident}={chunk}.split(b"\\x00", 1)[0].decode("{fp.field.string_encoding}", errors="replace")')
        elif fp.kind == "float":
            fmt = ("<" if fp.little else ">") + ("f" if fp.field.type == FieldType.FLOAT32 else "d")
            args.append(f'{fp.ident}=struct.unpack("{fmt}", {chunk})[0]')
        elif fp.kind == "int":
            args.append(f"{fp.ident}=_get_s({chunk}, {fp.little})")
        elif fp.kind == "bool":
            args.append(f"{fp.ident}=_get_u({chunk}, {fp.little}) != 0")
        else:
            args.append(f"{fp.ident}=_get_u({chunk}, {fp.little})")
    out.append(f"        return cls({', '.join(args)})")
    out += ["", ""]
    return out
